### ISSUE TITLE
not able to import modules withy Python 3 

### ISSUE THREAD

**Issue by benny3000** [RevaxZnarf/CoinTicker#2]
Hi there,
Thanks for your code, I really like this project and want to build it myself.
As I am a real noob to python, I do see issues with importing modules, even if they are in the same folder:
Traceback (most recent call last):
  File "/home/pi/CoinTicker/app/coin_ticker/run.py", line 4, in <module>
    from updater import Updater
  File "/home/pi/CoinTicker/app/coin_ticker/updater.py", line 2, in <module>
    from display import Display
  File "/home/pi/CoinTicker/app/coin_ticker/display.py", line 4, in <module>
    from waveshare_lib import epd2in13b
  File "/home/pi/CoinTicker/app/coin_ticker/waveshare_lib/epd2in13b.py", line 27, in <module>
    import epdif
ModuleNotFoundError: No module named 'epdif'

Do you have any idea, what this could be?
Thanks a lot in advance and kind regards!

**Comment by benny3000** [comment]
solved it myself, by moving the epd files one above into the app folder.
